spring:
  application:
    name: springboot-crud-api
  datasource:
    url: jdbc:sqlserver://localhost:32947;encrypt=false
    username: root
    password: root
logging:
  level:
    org.springframework.data.jdbc: debug
    sql: debug
